### ISSUE TITLE
Stack traces should not be printed in console 

### ISSUE THREAD

**Issue by akondasif** [daggerok/quarkus-examples#2]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/

Source: https://github.com/daggerok/quarkus-examples/blob/master/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/daggerok/quarkus-examples/pull/1

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by daggerok** [comment]
Hello @akondasif,

Thanks for contribution.
I've notice this fix is about maven wrapper, which is out of scope for that repository...
But anyway, it's merged.

---
Regards,
Maksim
